import { Card } from "@/features/types/cards";

export function createChanceDeck(): Card[] {
  return [
    {
      id: "chance-advance-to-go",
      deck: "chance",
      description: "Advance to GO.",
      type: "MOVE_TO",
      position: 0,
    },
    {
      id: "chance-go-to-jail",
      deck: "chance",
      description: "Go directly to Jail.",
      type: "GO_TO_JAIL",
    },
    {
      id: "chance-advance-to-illinois",
      deck: "chance",
      description: "Advance to Illinois Avenue.",
      type: "MOVE_TO",
      position: 24,
    },
    {
      id: "chance-advance-to-st-charles",
      deck: "chance",
      description: "Advance to St. Charles Place.",
      type: "MOVE_TO",
      position: 11,
    },
    {
      id: "chance-nearest-utility",
      deck: "chance",
      description: "Advance token to nearest Utility.",
      type: "ADVANCE_TO_NEAREST",
      target: "utility",
    },
    {
      id: "chance-nearest-railroad-1",
      deck: "chance",
      description: "Advance token to the nearest Railroad.",
      type: "ADVANCE_TO_NEAREST",
      target: "railroad",
    },
    {
      id: "chance-bank-dividend",
      deck: "chance",
      description: "Bank pays you dividend of $50.",
      type: "RECEIVE_FROM_BANK",
      amount: 50,
    },
    {
      id: "chance-get-out-of-jail-free",
      deck: "chance",
      description: "Get Out of Jail Free.",
      type: "GET_OUT_OF_JAIL_FREE",
    },
    {
      id: "chance-go-back-three",
      deck: "chance",
      description: "Go back 3 spaces.",
      type: "MOVE_RELATIVE",
      relative: -3,
    },
    {
      id: "chance-poor-tax",
      deck: "chance",
      description: "Pay poor tax of $15.",
      type: "PAY",
      amount: 15,
    },
    {
      id: "chance-chairman",
      deck: "chance",
      description: "You have been elected Chairman of the Board. Pay each player $50.",
      type: "PAY_EACH_PLAYER",
      amount: 50,
    },
    {
      id: "chance-reading-railroad",
      deck: "chance",
      description: "Take a trip to Reading Railroad.",
      type: "MOVE_TO",
      position: 5,
    },
    {
      id: "chance-boardwalk",
      deck: "chance",
      description: "Advance to Boardwalk.",
      type: "MOVE_TO",
      position: 39,
    },
    {
      id: "chance-nearest-railroad-2",
      deck: "chance",
      description: "Take a ride on the nearest Railroad.",
      type: "ADVANCE_TO_NEAREST",
      target: "railroad",
    },
    {
      id: "chance-building-loan",
      deck: "chance",
      description: "Your building loan matures. Collect $150.",
      type: "RECEIVE_FROM_BANK",
      amount: 150,
    },
    {
      id: "chance-general-repairs",
      deck: "chance",
      description: "Make general repairs on all your property.",
      type: "REPAIRS",
      houseAmount: 25,
      hotelAmount: 100,
    },
  ];
}

export function createCommunityChestDeck(): Card[] {
  return [
    {
      id: "community-advance-to-go",
      deck: "community",
      description: "Advance to GO.",
      type: "MOVE_TO",
      position: 0,
    },
    {
      id: "community-bank-error",
      deck: "community",
      description: "Bank error in your favor. Collect $200.",
      type: "RECEIVE_FROM_BANK",
      amount: 200,
    },
    {
      id: "community-doctors-fees",
      deck: "community",
      description: "Doctor's fees. Pay $50.",
      type: "PAY",
      amount: 50,
    },
    {
      id: "community-sale-of-stock",
      deck: "community",
      description: "From sale of stock you get $50.",
      type: "RECEIVE_FROM_BANK",
      amount: 50,
    },
    {
      id: "community-get-out-of-jail-free",
      deck: "community",
      description: "Get Out of Jail Free.",
      type: "GET_OUT_OF_JAIL_FREE",
    },
    {
      id: "community-go-to-jail",
      deck: "community",
      description: "Go directly to Jail.",
      type: "GO_TO_JAIL",
    },
    {
      id: "community-income-tax-refund",
      deck: "community",
      description: "Income tax refund. Collect $20.",
      type: "RECEIVE_FROM_BANK",
      amount: 20,
    },
    {
      id: "community-birthday",
      deck: "community",
      description: "It is your birthday. Collect $10 from every player.",
      type: "RECEIVE_EACH_PLAYER",
      amount: 10,
    },
    {
      id: "community-life-insurance",
      deck: "community",
      description: "Life insurance matures. Collect $100.",
      type: "RECEIVE_FROM_BANK",
      amount: 100,
    },
    {
      id: "community-hospital-fees",
      deck: "community",
      description: "Pay hospital fees of $50.",
      type: "PAY",
      amount: 50,
    },
    {
      id: "community-school-fees",
      deck: "community",
      description: "Pay school fees of $50.",
      type: "PAY",
      amount: 50,
    },
    {
      id: "community-consultancy-fee",
      deck: "community",
      description: "Receive $25 consultancy fee.",
      type: "RECEIVE_FROM_BANK",
      amount: 25,
    },
    {
      id: "community-street-repairs",
      deck: "community",
      description: "You are assessed for street repairs.",
      type: "REPAIRS",
      houseAmount: 40,
      hotelAmount: 115,
    },
    {
      id: "community-beauty-contest",
      deck: "community",
      description: "You have won second prize in a beauty contest. Collect $10.",
      type: "RECEIVE_FROM_BANK",
      amount: 10,
    },
    {
      id: "community-inherit",
      deck: "community",
      description: "You inherit $100.",
      type: "RECEIVE_FROM_BANK",
      amount: 100,
    },
    {
      id: "community-holiday-fund",
      deck: "community",
      description: "Holiday fund matures. Receive $100.",
      type: "RECEIVE_FROM_BANK",
      amount: 100,
    },
  ];
}
